#!/usr/bin/env python3
"""
SimAI自动化工作流 v1.0
整合所有工具，创建端到端的自动化仿真流程

Author: 二愣子 🤔
Date: 2026-02-20
"""

import os
import json
import subprocess
import time
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any, Optional


class AutomatedWorkflow:
    """SimAI自动化工作流引擎"""

    def __init__(self, workspace: str = None):
        """初始化工作流引擎"""
        self.workspace = Path(workspace) if workspace else Path.cwd()
        self.simai_dir = self.workspace / "SimAI"
        self.results_dir = self.workspace / "workflow_results"
        self.results_dir.mkdir(exist_ok=True)

        self.timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.session_id = f"workflow_{self.timestamp}"

        # 记录工作流状态
        self.state = {
            "session_id": self.session_id,
            "start_time": datetime.now().isoformat(),
            "status": "initialized",
            "steps_completed": [],
            "steps_failed": [],
            "results": {}
        }

    def log(self, message: str, level: str = "INFO"):
        """记录日志"""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        print(f"[{timestamp}] [{level}] {message}")
        self.state["results"].setdefault("logs", []).append({
            "time": timestamp,
            "level": level,
            "message": message
        })

    def step1_generate_workloads(self, config: Dict[str, Any]) -> List[Path]:
        """
        步骤1: 自动生成Workload
        """
        self.log("=" * 80)
        self.log("步骤1: 自动生成Workload")
        self.log("=" * 80)

        workload_dir = self.results_dir / "workloads"
        workload_dir.mkdir(exist_ok=True)

        # 生成配置
        scenarios = config.get("scenarios", [])
        if not scenarios:
            # 默认场景
            scenarios = [
                {"gpu_count": 8, "data_size": 16, "collective_ops": ["AllReduce"]},
                {"gpu_count": 16, "data_size": 64, "collective_ops": ["AllReduce"]},
                {"gpu_count": 32, "data_size": 256, "collective_ops": ["AllReduce"]},
            ]

        workload_files = []

        for i, scenario in enumerate(scenarios):
            gpu_count = scenario["gpu_count"]
            data_size = scenario["data_size"]
            ops = scenario["collective_ops"]

            # 生成workload文件
            workload_content = self._generate_workload_content(
                gpu_count, data_size, ops
            )

            workload_file = workload_dir / f"scenario_{i+1}_gpu{gpu_count}_s{data_size}.workload"
            with open(workload_file, 'w') as f:
                f.write(workload_content)

            workload_files.append(workload_file)
            self.log(f"  ✓ 生成Workload: {workload_file.name}")

        self.state["steps_completed"].append("generate_workloads")
        return workload_files

    def _generate_workload_content(self, gpu_count: int, data_size: int, ops: List[str]) -> str:
        """生成workload文件内容"""
        lines = [
            f"# GPU: {gpu_count}, Data: {data_size}MB, Ops: {ops}",
            f"# Generated by AutomatedWorkflow at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            f"num_iterations 1",
            ""
        ]

        for op in ops:
            lines.append(f"collective {op} {data_size * 1024 * 1024} 0 1")

        return "\n".join(lines)

    def step2_run_simulation(self, workload_files: List[Path]) -> List[Path]:
        """
        步骤2: 运行SimAI仿真
        """
        self.log("=" * 80)
        self.log("步骤2: 运行SimAI仿真")
        self.log("=" * 80)

        output_dir = self.results_dir / "simulation_outputs"
        output_dir.mkdir(exist_ok=True)

        output_files = []

        for workload_file in workload_files:
            self.log(f"  运行: {workload_file.name}")

            # 构建命令
            cmd = [
                os.path.join(self.simai_dir, "astra-sim-alibabacloud", "build", "analytical", "astra_analytical"),
                str(workload_file),
                os.path.join(self.simai_dir, "astra-sim-alibabacloud", "example", "0-MPICH-node", "01-pong", "astra-sim-input", "0-MPICH-node.json"),
                str(output_dir / workload_file.stem)
            ]

            try:
                # 运行仿真
                result = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    timeout=60
                )

                if result.returncode == 0:
                    self.log(f"    ✓ 成功: {workload_file.name}")
                    output_files.append(output_dir / f"{workload_file.stem}.txt")
                else:
                    self.log(f"    ✗ 失败: {workload_file.name}", level="ERROR")
                    self.log(f"      错误: {result.stderr[:200]}", level="ERROR")
                    self.state["steps_failed"].append(f"simulation_{workload_file.name}")

            except subprocess.TimeoutExpired:
                self.log(f"    ✗ 超时: {workload_file.name}", level="ERROR")
                self.state["steps_failed"].append(f"simulation_{workload_file.name}")
            except Exception as e:
                self.log(f"    ✗ 异常: {workload_file.name} - {e}", level="ERROR")
                self.state["steps_failed"].append(f"simulation_{workload_file.name}")

        self.state["steps_completed"].append("run_simulation")
        return output_files

    def step3_analyze_results(self, output_files: List[Path]) -> Dict[str, Any]:
        """
        步骤3: 分析仿真结果
        """
        self.log("=" * 80)
        self.log("步骤3: 分析仿真结果")
        self.log("=" * 80)

        analysis = {
            "total_runs": len(output_files),
            "successful_runs": 0,
            "failed_runs": 0,
            "results": []
        }

        for output_file in output_files:
            if not output_file.exists():
                analysis["failed_runs"] += 1
                continue

            try:
                with open(output_file, 'r') as f:
                    content = f.read()

                # 解析结果
                result = self._parse_simulation_output(content)
                result["file"] = output_file.name

                analysis["results"].append(result)
                analysis["successful_runs"] += 1

                self.log(f"  ✓ 分析: {output_file.name}")

            except Exception as e:
                self.log(f"  ✗ 分析失败: {output_file.name} - {e}", level="ERROR")
                analysis["failed_runs"] += 1

        self.state["steps_completed"].append("analyze_results")
        return analysis

    def _parse_simulation_output(self, content: str) -> Dict[str, Any]:
        """解析仿真输出"""
        result = {
            "total_time": 0.0,
            "collective_ops": []
        }

        for line in content.split('\n'):
            if "Time for Collective" in line or "Run time" in line:
                # 尝试提取时间
                parts = line.split()
                for i, part in enumerate(parts):
                    try:
                        time_val = float(part)
                        result["total_time"] = time_val
                        break
                    except ValueError:
                        continue

        return result

    def step4_optimize_parameters(self, analysis: Dict[str, Any]) -> Dict[str, Any]:
        """
        步骤4: 参数优化建议
        """
        self.log("=" * 80)
        self.log("步骤4: 参数优化建议")
        self.log("=" * 80)

        recommendations = {
            "bandwidth": {
                "current": "default",
                "recommended": "25 Gbps",
                "reason": "GPU集群标准带宽"
            },
            "latency": {
                "current": "default",
                "recommended": "10 μs",
                "reason": "NVLink低延迟网络"
            },
            "topology": {
                "current": "default",
                "recommended": "Fat-Tree",
                "reason": "大规模集群最优拓扑"
            },
            "algorithm": {
                "current": "auto",
                "recommended": "根据GPU规模选择",
                "guidance": {
                    "≤8 GPU": "RecursiveDoubling",
                    "8-32 GPU": "DoubleBinaryTree",
                    "≥32 GPU": "Hierarchical"
                }
            }
        }

        self.log("  优化建议:")
        self.log(f"    - 带宽: {recommendations['bandwidth']['recommended']}")
        self.log(f"    - 延迟: {recommendations['latency']['recommended']}")
        self.log(f"    - 拓扑: {recommendations['topology']['recommended']}")
        self.log(f"    - 算法: {recommendations['algorithm']['guidance']}")

        self.state["steps_completed"].append("optimize_parameters")
        return recommendations

    def step5_generate_report(self, analysis: Dict[str, Any], recommendations: Dict[str, Any]) -> Path:
        """
        步骤5: 生成完整报告
        """
        self.log("=" * 80)
        self.log("步骤5: 生成完整报告")
        self.log("=" * 80)

        # Markdown报告
        md_report = self._generate_markdown_report(analysis, recommendations)
        md_file = self.results_dir / f"WORKFLOW_REPORT_{self.timestamp}.md"

        with open(md_file, 'w', encoding='utf-8') as f:
            f.write(md_report)

        # JSON报告
        json_report = {
            "session_id": self.session_id,
            "timestamp": self.timestamp,
            "analysis": analysis,
            "recommendations": recommendations,
            "state": self.state
        }
        json_file = self.results_dir / f"WORKFLOW_REPORT_{self.timestamp}.json"

        with open(json_file, 'w', encoding='utf-8') as f:
            json.dump(json_report, f, indent=2, ensure_ascii=False)

        self.log(f"  ✓ Markdown报告: {md_file.name}")
        self.log(f"  ✓ JSON报告: {json_file.name}")

        self.state["steps_completed"].append("generate_report")
        return md_file

    def _generate_markdown_report(self, analysis: Dict[str, Any], recommendations: Dict[str, Any]) -> str:
        """生成Markdown报告"""
        lines = [
            "# SimAI自动化工作流报告",
            "",
            f"**会话ID**: {self.session_id}",
            f"**生成时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "## 1. 执行摘要",
            "",
            f"- 总测试数: {analysis.get('total_runs', 0)}",
            f"- 成功: {analysis.get('successful_runs', 0)}",
            f"- 失败: {analysis.get('failed_runs', 0)}",
            "",
            "## 2. 仿真结果",
            ""
        ]

        for result in analysis.get("results", []):
            lines.append(f"### {result.get('file', 'Unknown')}")
            lines.append(f"- 总时间: {result.get('total_time', 0):.6f} ms")
            lines.append("")

        lines.extend([
            "## 3. 优化建议",
            "",
            "### 带宽配置",
            f"- 推荐: {recommendations['bandwidth']['recommended']}",
            f"- 理由: {recommendations['bandwidth']['reason']}",
            "",
            "### 延迟配置",
            f"- 推荐: {recommendations['latency']['recommended']}",
            f"- 理由: {recommendations['latency']['reason']}",
            "",
            "### 拓扑选择",
            f"- 推荐: {recommendations['topology']['recommended']}",
            f"- 理由: {recommendations['topology']['reason']}",
            "",
            "### 算法选择",
            f"- 推荐: {recommendations['algorithm']['recommended']}",
            "",
            "根据GPU规模选择:",
            ""
        ])

        for gpu_range, algo in recommendations['algorithm']['guidance'].items():
            lines.append(f"- {gpu_range}: {algo}")

        lines.extend([
            "",
            "## 4. 工作流状态",
            "",
            f"**完成步骤**: {', '.join(self.state['steps_completed'])}",
            "",
            f"**失败步骤**: {', '.join(self.state['steps_failed']) if self.state['steps_failed'] else '无'}",
            "",
            "---",
            "",
            f"*报告由 SimAI自动化工作流 v1.0 生成*",
            f"*生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*"
        ])

        return "\n".join(lines)

    def run_full_workflow(self, config: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        运行完整工作流
        """
        self.log("🚀 启动SimAI自动化工作流")
        self.log(f"会话ID: {self.session_id}")
        self.log("=" * 80)

        start_time = time.time()

        try:
            # 步骤1: 生成Workload
            workload_files = self.step1_generate_workloads(config or {})

            if not workload_files:
                raise Exception("未能生成任何Workload文件")

            # 步骤2: 运行仿真
            output_files = self.step2_run_simulation(workload_files)

            # 步骤3: 分析结果
            analysis = self.step3_analyze_results(output_files)

            # 步骤4: 参数优化
            recommendations = self.step4_optimize_parameters(analysis)

            # 步骤5: 生成报告
            report_file = self.step5_generate_report(analysis, recommendations)

            elapsed_time = time.time() - start_time

            self.state["status"] = "completed"
            self.state["end_time"] = datetime.now().isoformat()
            self.state["elapsed_time"] = elapsed_time
            self.state["report_file"] = str(report_file)

            self.log("=" * 80)
            self.log("✅ 工作流完成!")
            self.log(f"总耗时: {elapsed_time:.2f}秒")
            self.log(f"报告: {report_file}")
            self.log("=" * 80)

            return self.state

        except Exception as e:
            self.state["status"] = "failed"
            self.state["error"] = str(e)
            self.log(f"❌ 工作流失败: {e}", level="ERROR")
            raise


def main():
    """主函数"""
    import argparse

    parser = argparse.ArgumentParser(description="SimAI自动化工作流")
    parser.add_argument("--workspace", type=str, default=".",
                       help="工作空间目录（默认: 当前目录）")
    parser.add_argument("--gpu-counts", type=str, default="8,16,32",
                       help="GPU数量列表，逗号分隔（默认: 8,16,32）")
    parser.add_argument("--data-sizes", type=str, default="16,64,256",
                       help="数据大小列表（MB），逗号分隔（默认: 16,64,256）")
    parser.add_argument("--ops", type=str, default="AllReduce",
                       help="集合操作，逗号分隔（默认: AllReduce）")

    args = parser.parse_args()

    # 解析参数
    gpu_counts = [int(x) for x in args.gpu_counts.split(',')]
    data_sizes = [int(x) for x in args.data_sizes.split(',')]
    ops = args.ops.split(',')

    # 生成场景
    scenarios = []
    for gpu in gpu_counts:
        for data in data_sizes:
            scenarios.append({
                "gpu_count": gpu,
                "data_size": data,
                "collective_ops": ops
            })

    config = {
        "scenarios": scenarios
    }

    # 运行工作流
    workflow = AutomatedWorkflow(workspace=args.workspace)
    result = workflow.run_full_workflow(config)

    print("\n" + "=" * 80)
    print("工作流执行完成!")
    print(f"状态: {result['status']}")
    print(f"耗时: {result.get('elapsed_time', 0):.2f}秒")
    print(f"报告: {result.get('report_file', 'N/A')}")
    print("=" * 80)


if __name__ == "__main__":
    main()
